fix(docker): Set the permission for the log4j.properties file
I don't know why this suddenly became an issue, but the problem was that in
the container the file /etc/opt/jetty/resources/log4j.properties was getting
created with root as its owner. This makes sense according to the previous
docker file, which didn't set its ownership. When you do that, the owner is
root. But what's weird is that this suddenly began throwing an error in the
logs:

    ↪ cd /home/mlissner/Programming/test3/courtlistener-solr-server/ && docker run --volume /home/mlissner/Programming/test3/courtlistener-solr-server/solr/cores:/etc/opt/solr:ro --volume /home/mlissner/Programming/test3/courtlistener-solr-server/data:/var/opt/solr/indices -p 8983:8983 --log-driver journald freelawproject/solr:0.6.3
    log4j:ERROR Could not read configuration file from URL [file:/etc/opt/jetty/resources/log4j.properties].
    java.io.FileNotFoundException: /etc/opt/jetty/resources/log4j.properties (Permission denied)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:557)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:66)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:277)
        at org.eclipse.jetty.util.log.Slf4jLog.<init>(Slf4jLog.java:38)
        at org.eclipse.jetty.util.log.Slf4jLog.<init>(Slf4jLog.java:32)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.eclipse.jetty.util.log.Log.initialized(Log.java:161)
        at org.eclipse.jetty.util.log.Log.getLogger(Log.java:435)
        at org.eclipse.jetty.util.log.Log.getLogger(Log.java:425)
        at org.eclipse.jetty.xml.XmlConfiguration.<clinit>(XmlConfiguration.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jetty.start.Main.invokeMain(Main.java:473)
        at org.eclipse.jetty.start.Main.start(Main.java:615)
        at org.eclipse.jetty.start.Main.main(Main.java:96)
    log4j:ERROR Ignoring configuration file [file:/etc/opt/jetty/resources/log4j.properties].
    log4j:WARN No appenders could be found for logger (org.eclipse.jetty.util.log).
    log4j:WARN Please initialize the log4j system properly.
    log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

In other words no logging config can be read, so we can't do any logging. Well,
that's obviously not great. The file was there, but it was owned by root and the
group and others didn't have permission to read it. The easy fix here is to just
set the owner of the file, as I've done.

A couple annoyances though:

1. I don't know why this broke. Nothing much in the code changed. It's possible
that Java8, the base for this image changed? Maybe. I haven't been able to
figure out what changed though, and that annoys me.

2. I'd love to do this as --chown=${SOLR_USER} or something like that, buuuuut,
that's not possible because docker. Supposedly this is supported in 19.3.03,
which is what I've got, but, well, it doesn't work, so fuck it. Hopefully nobody
will regret this down the road.